---
- name: docker-build-push
  hosts: docker
  become: true

  vars:
    dockerhub_username: kishore18111997
    dockerhub_password: dckr_pat_vMIyAbJdfl-K_yAzmiywXEis2Ws
    image_name: kishore18111997/tomcatproject
    image_tag: 1

  tasks:
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: cd /opt/docker

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: docker build -t kishore18111997/tomcatproject .

  - name: Log into DockerHub
    docker_login:
      username: kishore18111997
      password: dckr_pat_vMIyAbJdfl-K_yAzmiywXEis2Ws

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: docker push kishore18111997/tomcatproject
