---
- name: install apache2
  hosts: slave1
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
    - name: start apache2
      service:
        name: apache2
        state: started
